### ISSUE TITLE
_createClass is not defined

### ISSUE THREAD

**Issue by bannik** [ericwooley/react-in-style#12]
This is an error i am getting when I run my app on chrome without opening inspect element first:

Uncaught ReferenceError: _createClass is not defined

If I refresh with inspect element open the app works just fine

**Comment by ericwooley** [comment]
Any chance you can post a full stack trace?

**Comment by aidangarza** [comment]
Sorry, it's been too long. I don't have it in my app anymore.

AIDAN GARZA
UX Architect & Front-End Developer
aidangarza@gmail.com
1 (623) 396-6289
www.aidangarza.com

**Comment by ericwooley** [comment]
I will open this again if anyone reports it.
